### ISSUE TITLE
In which cases the performer is the hash of email address?

### ISSUE THREAD

**Issue by bearxy39** [OfficeDev/o365-actionable-messages-utilities-for-dotnet#7]
https://github.com/OfficeDev/o365-actionable-messages-utilities-for-dotnet/blob/c0e82ec87214d5c75fb2e7212f663e54b4f199aa/src/Microsoft.O365.ActionableMessages.Utilities/ActionableMessageTokenValidationResult.cs#L44-L45

We use ActionPerformer to verify if the request comes from the correct user, following the example code. When ActionPerformer is the hash of email address, the verification will fail. Could anyone explain the situations?

**Comment by wowong** [comment]
One possible situation is that O365 is not able to resolve the email address of the person who performed the action. But this is a very rare condition. The safe thing to do is, if the ActionPerformer email address does not exist in the database or authorized list, the system should assume the ActionPerformer is unauthorized and reject the action.

**Comment by davidchesnut** [comment]
I'm closing this issue since the repo is being archived.
